project:
  type: book
  output-dir: _book

book:
  title: "数据挖掘与机器学习课程讲义"
  author: "汪小圈" # 请替换为您的姓名
  date: last-modified
  chapters:
    - index.qmd
    - 01_ml_basic.qmd
    - lab02_data.qmd
    - 03_supervised.qmd
    - 04_supervised.qmd
    - 05_model_assess.qmd
    - lab03_titanic.qmd
    - 06_credit.qmd
    - 07_unsupervised.qmd
    - 07_cluster.qmd
    - lab07_cluster.qmd
    - project1_LC.qmd
    - project2a_tspred.qmd
    - project2b_text.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    number-sections: true
    toc: true
    toc-depth: 3
    lang: zh-CN

execute:
  freeze: auto 